name: Build Image

on:
  push:
    #branches: [ main ]
  pull_request:
    #branches: [ main ]

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/kabam-adriennec/testpackage:test7
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_LOGIN }}" | docker login ghcr.io -u kabam-adriennec --password-stdin
      - name: Push image 
        run: docker tag ghcr.io/kabam-adriennec/testpackage:test7 ghcr.io/kabam-adriennec/testpackage:test6
      - name: push image to  new tag
        run: docker push ghcr.io/kabam-adriennec/testpackage:test6
      - name: Push image
        run: docker push ghcr.io/kabam-adriennec/testpackage:test7
      