name: Build Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: "testpackage"
  #NODE_ENV: production
  TAG_NAME: "ghcr.io/kabam-adriennec/testpackage"

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        #run: docker build --tag ${IMAGE_NAME} --build-arg GITHUB_AUTH_TOKEN=${{ secrets.SPARX_ROBOT_PAT }} .
        run: docker build . --file app/Dockerfile --tag ghcr.io/kabam-adriennec/testpackage:latest
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_LOGIN }}" | docker login ghcr.io -u kabam-adriennec --password-stdin
  
